spring.application.name=servicio-opiniones
server.port=8098

# Conexión a DB Opiniones
spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_opiniones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Ruta donde se generará el JSON de la documentación (Mapeado a tus opiniones)
springdoc.api-docs.path=/opiniones/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Indicar a Spring que respete los encabezados X-Forwarded que inyecta el API Gateway
server.forward-headers-strategy=framework

# Ayuda a SpringDoc a entender que el prefijo en las peticiones externas es /opiniones
springdoc.webjars.prefix=/opiniones
# Fuerza a SpringDoc a usar las cabeceras de reenvío
springdoc.use-management-port=false
springdoc.show-actuator=false

# Configuración de Tomcat para interceptar el tráfico redirigido del Gateway correctamente
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port