server:
  port: 9090

jwt:
  secret: "493322258340235739058340598340598340598340598340598"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      
      routes:
        # 1. Clientes
        - id: clientes-docs
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/clientes/v3/api-docs
        - id: clientes-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/clientes/**
          filters:
            - AuthenticationFilter

        # 2. Productos
        - id: productos-docs
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/productos/v3/api-docs
        - id: productos-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/productos/**
          filters:
            - AuthenticationFilter

        # 3. Pagos
        - id: pagos-docs
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/pagos/v3/api-docs
        - id: pagos-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/pagos/**
          filters:
            - AuthenticationFilter

        # 4. Pedidos
        - id: pedidos-docs
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/pedidos/v3/api-docs
        - id: pedidos-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/pedidos/**
          filters:
            - AuthenticationFilter

        # 5. Usuarios
        - id: usuarios-docs
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/usuarios/v3/api-docs
        - id: usuarios-registro
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/usuarios/registrar
        - id: usuarios-login
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/usuarios/login
        - id: usuarios-service
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - AuthenticationFilter

        # 6. Despachos
        - id: despachos-docs
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/despachos/v3/api-docs
        - id: servicio-despachos
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/despachos/**
          filters:
            - AuthenticationFilter

        # 7. Inventario
        - id: inventario-docs
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/inventario/v3/api-docs
        - id: servicio-inventario
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/inventario/**
          filters:
            - AuthenticationFilter

        # 8. Notificaciones
        - id: notificaciones-docs
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/notificaciones/v3/api-docs
        - id: servicio-notificaciones
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - AuthenticationFilter

        # 9. Reportes
        - id: reportes-docs
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/reportes/v3/api-docs
        - id: servicio-reportes
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/reportes/**
          filters:
            - AuthenticationFilter

        # 10. Opiniones
        - id: opiniones-docs
          uri: http://localhost:8098
          predicates:
            - Path=/api/v1/opiniones/v3/api-docs
        - id: servicio-opiniones
          uri: http://localhost:8098
          predicates:
            - Path=/api/v1/opiniones/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: 1. Servicio Clientes
        url: /api/v1/clientes/v3/api-docs
      - name: 2. Servicio Productos
        url: /api/v1/productos/v3/api-docs
      - name: 3. Servicio Pagos
        url: /api/v1/pagos/v3/api-docs
      - name: 4. Servicio Pedidos
        url: /api/v1/pedidos/v3/api-docs
      - name: 5. Servicio Usuarios
        url: /api/v1/usuarios/v3/api-docs
      - name: 6. Servicio Despachos
        url: /api/v1/despachos/v3/api-docs
      - name: 7. Servicio Inventario
        url: /api/v1/inventario/v3/api-docs
      - name: 8. Servicio Notificaciones
        url: /api/v1/notificaciones/v3/api-docs
      - name: 9. Servicio Reportes
        url: /api/v1/reportes/v3/api-docs
      - name: 10. Servicio Opiniones
        url: /api/v1/opiniones/v3/api-docs