# Nombre de mi microservicio 
spring.application.name=proyecto
# Puerto nuevo el 8081 está bloqueado en la U
server.port=8091

# Configuración de Base de Datos (XAMPP) aqui ocurre la magia de conectarse
spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_clientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true