spring.application.name=proyecto
server.port=8091
spring.profiles.active=local

# Base de datos local de desarrollo (H2 en memoria)
spring.datasource.url=jdbc:h2:mem:db_lart_clientes;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estrategia para Gateway <3
server.forward-headers-strategy=framework
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port

# Mapeo unificado para Swagger OpenAPI <3
springdoc.api-docs.path=/api/v1/clientes/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html