spring.application.name=service-auth
server.port=8095
spring.datasource.url=jdbc:mysql://localhost:3306/db_usuario
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Llave secreta para firmar el Token (Mínimo 32 caracteres)
jwt.secret=493322258340235739058340598340598340598340598340598

# PARA APAGAR EL BLOQUEO:
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
