spring.application.name=service-pedidos
server.port=8094

spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_pedidos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Indicar a Spring que respete los encabezados X-Forwarded Host, Port, Proto
server.forward-headers-strategy=framework

# Configuracion unificada para mapear la documentacion a traves del Gateway
springdoc.api-docs.path=/api/v1/pedidos/v3/api-docs

# Configuracion de Tomcat para interceptar las cabeceras del Gateway 
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port