spring.application.name=service-pago
server.port=8094
spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_pagos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Indicar a Spring que respete los encabezados X-Forwarded (Host, Port, Proto)
server.forward-headers-strategy=framework
# Ayuda a SpringDoc a entender que hay un prefijo desde el Gateway
springdoc.webjars.prefix=/api/v1/pacientes
# Fuerza a SpringDoc a usar las cabeceras X-Forwarded
springdoc.use-management-port=false
springdoc.show-actuator=false

# Esta línea es la que suele arreglar el problema cuando el strategy=framework falla
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port