spring.application.name=service-pago
server.port=8094
spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_pagos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.forward-headers-strategy=framework

springdoc.webjars.prefix=/api/v1/pagos

springdoc.use-management-port=false
springdoc.show-actuator=false

server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port