spring.application.name=servicio-notificaciones
# Elegimos este puerto al azar ya que es el ultimo microservicio
server.port=8071

spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_notificaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true