spring.application.name=service-productos
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/db_lart_productos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Estrategia para Gateway
server.forward-headers-strategy=framework
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port

# Mapeo unificado para Swagger OpenAPI
springdoc.api-docs.path=/api/v1/productos/v3/api-docs